### ISSUE TITLE
Errors in test file

### ISSUE THREAD

**Issue by ZhichaoC** [angeliama98/CS4500-A1-Part2#10]
There are so typos in test file:

- Line 27: length

- Line 34: true

- Line 44: println?

In test 1, can you explain why array a != array b?
In test 2, remove takes in a string, which should be an index according to the api
In test 2, set method need a valid index according to the description "set the element in the given index to the given object", and index 1 is not exist at line 31.
In test 3, testing two hashes of an item are equal?
In test 4, append array (according to api return an array pointer, so I am assuming not modify existing array), but the test seems modify existing array.
In test 5, index of u should be 2

**Comment by angeliama98** [comment]
For test 4, yes, it changes the existing array. The array pointer we return should be 'this' array. Other typo and test cases have been fixed.
