### ISSUE TITLE
Behavior of set

### ISSUE THREAD

**Issue by chasebroder** [angeliama98/CS4500-A1-Part2#11]
Hi. I was wondering if I could get a clarification about the set method. I'm not too sure if it's supposed to insert into the array or modify existing elements.

So let's say you have a list {"hello", "world", "hello world"} and you call set(1, "goodbye"). Would the result be an insertion {"hello", "goodbye", "world", "hello world"} or would it overwrite the existing element there {"hello", "goodbye", "hello world"}?

**Comment by angeliama98** [comment]
{"hello", "goodbye", "hello world"}
