### ISSUE TITLE
array.h contains fields && object.h has two hash functions

### ISSUE THREAD

**Issue by ZhichaoC** [angeliama98/CS4500-A1-Part2#2]
Since we are expected to give api, I don't think there should be any implementation (and fields) in the api. 
In addition, can you explain why object has two hash functions?

**Comment by ZhichaoC** [comment]
Also, can we have all functions being virtual so that we can override them for array of int, bool, float, etc

**Comment by ZhichaoC** [comment]
Can we have object.h and string.h to be standard that we can use across three structures?

[suggested data type.zip](https://github.com/angeliama98/CS4500-A1-Part2/files/4119135/suggested.data.type.zip)

**Comment by mkierzenka** [comment]
> 
> 
> Can we have object.h and string.h to be standard that we can use across three structures?
> 
> [suggested data type.zip](https://github.com/angeliama98/CS4500-A1-Part2/files/4119135/suggested.data.type.zip)

The code attached above seems mostly okay to us, for now. We would like to request the method is renamed to "length" instead of "get_length" as that is more standard.

**Comment by ZhichaoC** [comment]
That works, thanks
