### ISSUE TITLE
Why arrray.add return an object pointer?

### ISSUE THREAD

**Issue by ZhichaoC** [angeliama98/CS4500-A1-Part2#3]
Why arrray.add return an object pointer? should it be just void?

**Comment by angeliama98** [comment]
So, we can have the object pointer as output. If we need it to embedded inside of other functions, it can also work as an input.

**Comment by ZhichaoC** [comment]
So the input would be the output? If that's the case, why we need an output?

**Comment by angeliama98** [comment]
For instance, you can do l->set(0,l->add("hi")). It will help to add "hi" to the list and set it with 0 index. If we make l->add("hi") be void, the function can only work by itself. And it will not allow the functionality I showed above.

**Comment by ZhichaoC** [comment]
l->add("hi") adds the string to the end of the list. I->set(0, l->add("hi")) would add string "hi" to both replace front element and insert the element to the end of the list (for example, [hello, world, come] -> [hi, world, come, hi]). I am not sure if this is intended. However, returning a pointer to the element in the array by add operation is somewhat undesired because this implies we can modify the element in the list without explicit set/remove operation (which intended to mutate the list).
You can achieve the goal you demonstrated above by either perform (add, get last element, then set) or string hi, add hi, set 0 hi. It's very ambiguous to demonstrate  this operation "l->set(0,l->add("hi"))" when other people read the code.

**Comment by angeliama98** [comment]
ok. I see what you mean now. I will change it to void.

**Comment by mkierzenka** [comment]
Nudge, this was never changed to void.
