### ISSUE TITLE
Proposed change: have Array inherit from object

### ISSUE THREAD

**Issue by chasebroder** [angeliama98/CS4500-A1-Part2#4]
Hello,

We'd like to have Array inherit from the Object class. This way, you could either use or override the equals and hash functions provided by Object, rather than having to make new ones. Let us know what you think of this change!

Thanks,
Chase

**Comment by angeliama98** [comment]
Hi,

I think hash_me() in our API is what you want. It has 'virtual' keyword.

**Comment by ZhichaoC** [comment]
I think it would be a good idea to make everything an object so that we can call equals and hash. It's little bit redundant to have equals and hash in both array and object

**Comment by angeliama98** [comment]
We need to check the hash of the object and object itself to make sure it equals the other object. The same thing applies to an array. Object and array should have a different hash function to guarantee they don't generate same hash code.

**Comment by ZhichaoC** [comment]
Umm, then you can override the hash function for array. Having array not inherit object does not guarantee they have different hash (i.e. object hash(){return 1} does not prevent array hash(){return 1} even no inheritance).

**Comment by angeliama98** [comment]
changed it.
