### ISSUE TITLE
Proposed change: add Array classes for Strings and primitives

### ISSUE THREAD

**Issue by chasebroder** [angeliama98/CS4500-A1-Part2#5]
Hello,

We'd like to add four new Array classes: StringArray, FloatArray, IntArray, and BoolArray. The goal is to have the functions for this class tailored to each specific type. Unfortunately this would result in some code duplication. We'd need similar methods for each, but they wouldn't be reusable, as you'd have to take in the specific data type for that class (ex. IntArray's set method would have to take in an int, rather than an Object* like in Array). 

Per Piazza post 331 (https://piazza.com/class/k51bluky59n2jr?cid=331) and the resulting conversation, it appears that we should be able to pass primitive types directly to the array. We believe that the proposed structure would be the most effective way to allow this. With the current Array interface, you would need to box the primitives. 

Let us know what you think and reach out if you have additional questions!

Best,
Chase

**Comment by angeliama98** [comment]
I would like to stick with the one Array design for now. Array should be capable of taking in objects that can hold the wrappers and that's all this assignment asks for. And it will also prevent code duplication.
